---

- name: Install the components
  apt:
    name: "{{ item }}"
  with_items:
    - neutron-linuxbridge-agent

- name: Configure the Neutron service
  ini_file: 
    path: /etc/neutron/neutron.conf
    section: "{{ item.0.name }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
  with_subelements:
    - "{{ neutron_conf }}"
    - attributes

- name: Configure the linux bridge agent
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{ item.0.name }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
  with_subelements:
    - "{{ linuxbridge_agent }}"
    - attributes
 
- name: Configure Nova to use Netron service
  ini_file:
    path: /etc/nova/nova.conf
    section: "{{ item.0.name }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
  with_subelements:
    - "{{ nova_conf }}"
    - attributes

- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent
