---

# Install and configure Chrony

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Remove pool 2.debian.pool.ntp.org offline iburst
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: pool 2.debian.pool.ntp.org offline iburst
    state: absent

- name: Configure iburst ntp server for controller node
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: "server {{ item }} iburst"
  with_items: 
    - 1.vn.pool.ntp.org
    - 0.asia.pool.ntp.org
    - 3.asia.pool.ntp.org

- name: Allow connections to the private network 
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: "allow {{ PRIVATE_NETWORK  }}"
    create: yes

- name: Restart NTP service 
  service:
    name: chrony
    state: restarted


# Install and configure openstack Pike packages

- name: Install software-properties-common
  apt:
    name: software-properties-common

- name: Add Pike repository
  command: "add-apt-repository cloud-archive:pike"

- name: Install openstack client
  apt:
    name: python-openstackclient
    update_cache: yes
    state: latest


# Install and configure sql database

- name: Install mariadb and pymysql
  apt:
    name: "{{ item }}"
  with_items:
    - mariadb-server
    - python-pymysql
    - python3-mysqldb

- name: Configure mariadb
  ini_file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    create: yes
    section: mysqld
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    bind-address: "{{ PRIVATE_ADDRESS }}"
    default-storage-engine: innodb
    innodb_file_per_table: on
    max_connections: 4096
    collation-server: utf8_general_ci
    character-set-server: utf8

- name: Restart mysql service
  service:
    name: mysql
    state: restarted


# Install and configure rabbitmq

- name: Install rabbitmq
  apt:
    name: rabbitmq-server

- name: Add openstack user and add conf, read and write permissions to it
  command: "{{ item }}"
  with_items: 
    - "rabbitmqctl add_user openstack {{ RABBIT_PASS }}"
    - "rabbitmqctl set_permissions openstack '.*' '.*' '.*'"


# Install and configure memory cache

- name: Install memcache
  apt:
    name: "{{ item }}"
  with_items:
    - memcached
    - python-memcache

- name: Remove previous configuration
  lineinfile:
    path: /etc/memcached.conf
    line: "-l 127.0.0.1"
    state: absent

- name: Configure memcache 
  lineinfile:
    path: /etc/memcached.conf
    line: "-l {{ PRIVATE_ADDRESS }}"
    state: absent

- name: Restart service
  service:
    name: memcached
    state: restarted
